package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSmPhotoCollectionRecord<M extends BaseSmPhotoCollectionRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCollectionId(java.lang.Integer collectionId) {
		set("collectionId", collectionId);
		return (M)this;
	}
	
	public java.lang.Integer getCollectionId() {
		return getInt("collectionId");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("projectId", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("projectId");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

}
