package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFeedback<M extends BaseFeedback<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAccountName(java.lang.String accountName) {
		set("accountName", accountName);
		return (M)this;
	}
	
	public java.lang.String getAccountName() {
		return getStr("accountName");
	}

	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}
	
	public java.lang.String getAccount() {
		return getStr("account");
	}

	public M setAccountType(java.lang.Integer accountType) {
		set("accountType", accountType);
		return (M)this;
	}
	
	public java.lang.Integer getAccountType() {
		return getInt("accountType");
	}

	public M setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
		return (M)this;
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

}
