package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSensitiveWords<M extends BaseSensitiveWords<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWord(java.lang.String word) {
		set("word", word);
		return (M)this;
	}
	
	public java.lang.String getWord() {
		return getStr("word");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setWordPinyin(java.lang.String wordPinyin) {
		set("word_pinyin", wordPinyin);
		return (M)this;
	}
	
	public java.lang.String getWordPinyin() {
		return getStr("word_pinyin");
	}

}
