package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClasses<M extends BaseClasses<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSchoolId(java.lang.Integer schoolId) {
		set("schoolId", schoolId);
		return (M)this;
	}
	
	public java.lang.Integer getSchoolId() {
		return getInt("schoolId");
	}

	public M setLogo(java.lang.String logo) {
		set("logo", logo);
		return (M)this;
	}
	
	public java.lang.String getLogo() {
		return getStr("logo");
	}

	public M setGradeId(java.lang.Integer gradeId) {
		set("gradeId", gradeId);
		return (M)this;
	}
	
	public java.lang.Integer getGradeId() {
		return getInt("gradeId");
	}

	public M setTeacherId(java.lang.Integer teacherId) {
		set("teacherId", teacherId);
		return (M)this;
	}
	
	public java.lang.Integer getTeacherId() {
		return getInt("teacherId");
	}

	public M setMotto(java.lang.String motto) {
		set("motto", motto);
		return (M)this;
	}
	
	public java.lang.String getMotto() {
		return getStr("motto");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

}
