package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSchool<M extends BaseSchool<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAdminId(java.lang.Integer adminId) {
		set("adminId", adminId);
		return (M)this;
	}
	
	public java.lang.Integer getAdminId() {
		return getInt("adminId");
	}

	public M setLogo(java.lang.String logo) {
		set("logo", logo);
		return (M)this;
	}
	
	public java.lang.String getLogo() {
		return getStr("logo");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setArea(java.lang.String area) {
		set("area", area);
		return (M)this;
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}

	public M setContact(java.lang.String contact) {
		set("contact", contact);
		return (M)this;
	}
	
	public java.lang.String getContact() {
		return getStr("contact");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setLeader(java.lang.String leader) {
		set("leader", leader);
		return (M)this;
	}
	
	public java.lang.String getLeader() {
		return getStr("leader");
	}

	public M setParentCount(java.lang.Long parentCount) {
		set("parentCount", parentCount);
		return (M)this;
	}
	
	public java.lang.Long getParentCount() {
		return getLong("parentCount");
	}

	public M setClassCount(java.lang.Long classCount) {
		set("classCount", classCount);
		return (M)this;
	}
	
	public java.lang.Long getClassCount() {
		return getLong("classCount");
	}

	public M setStudentCount(java.lang.Long studentCount) {
		set("studentCount", studentCount);
		return (M)this;
	}
	
	public java.lang.Long getStudentCount() {
		return getLong("studentCount");
	}

	public M setTeacherCount(java.lang.Long teacherCount) {
		set("teacherCount", teacherCount);
		return (M)this;
	}
	
	public java.lang.Long getTeacherCount() {
		return getLong("teacherCount");
	}

	public M setJoinAt(java.util.Date joinAt) {
		set("joinAt", joinAt);
		return (M)this;
	}
	
	public java.util.Date getJoinAt() {
		return get("joinAt");
	}

	public M setNextPayAt(java.util.Date nextPayAt) {
		set("nextPayAt", nextPayAt);
		return (M)this;
	}
	
	public java.util.Date getNextPayAt() {
		return get("nextPayAt");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public M setUpdateAt(java.util.Date updateAt) {
		set("updateAt", updateAt);
		return (M)this;
	}
	
	public java.util.Date getUpdateAt() {
		return get("updateAt");
	}

}
