package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSchoolId(java.lang.Integer schoolId) {
		set("schoolId", schoolId);
		return (M)this;
	}
	
	public java.lang.Integer getSchoolId() {
		return getInt("schoolId");
	}

	public M setTeacherCode(java.lang.String teacherCode) {
		set("teacherCode", teacherCode);
		return (M)this;
	}
	
	public java.lang.String getTeacherCode() {
		return getStr("teacherCode");
	}

	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setSubject(java.lang.String subject) {
		set("subject", subject);
		return (M)this;
	}
	
	public java.lang.String getSubject() {
		return getStr("subject");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setStartTeachDate(java.util.Date startTeachDate) {
		set("startTeachDate", startTeachDate);
		return (M)this;
	}
	
	public java.util.Date getStartTeachDate() {
		return get("startTeachDate");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public M setUpdateAt(java.util.Date updateAt) {
		set("updateAt", updateAt);
		return (M)this;
	}
	
	public java.util.Date getUpdateAt() {
		return get("updateAt");
	}

}
