package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysSession<M extends BaseSysSession<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
		return (M)this;
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	public M setExpireAt(java.lang.Long expireAt) {
		set("expireAt", expireAt);
		return (M)this;
	}
	
	public java.lang.Long getExpireAt() {
		return getLong("expireAt");
	}

	public M setCareateAt(java.util.Date careateAt) {
		set("careateAt", careateAt);
		return (M)this;
	}
	
	public java.util.Date getCareateAt() {
		return get("careateAt");
	}

}
