package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysInfo<M extends BaseSysInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setCover(java.lang.String cover) {
		set("cover", cover);
		return (M)this;
	}
	
	public java.lang.String getCover() {
		return getStr("cover");
	}

	public M setAdminId(java.lang.Integer adminId) {
		set("adminId", adminId);
		return (M)this;
	}
	
	public java.lang.Integer getAdminId() {
		return getInt("adminId");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setReadCount(java.lang.Integer readCount) {
		set("readCount", readCount);
		return (M)this;
	}
	
	public java.lang.Integer getReadCount() {
		return getInt("readCount");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("isDelete", isDelete);
		return (M)this;
	}
	
	public java.lang.Boolean getIsDelete() {
		return get("isDelete");
	}

	public M setFieldId(java.lang.Integer fieldId) {
		set("fieldId", fieldId);
		return (M)this;
	}
	
	public java.lang.Integer getFieldId() {
		return getInt("fieldId");
	}

}
