package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSmSysMeassage<M extends BaseSmSysMeassage<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSenderId(java.lang.Integer senderId) {
		set("senderId", senderId);
		return (M)this;
	}
	
	public java.lang.Integer getSenderId() {
		return getInt("senderId");
	}

	public M setRecipientid(java.lang.Integer recipientid) {
		set("recipientid", recipientid);
		return (M)this;
	}
	
	public java.lang.Integer getRecipientid() {
		return getInt("recipientid");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

}
