package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSmPhotoComment<M extends BaseSmPhotoComment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWorksId(java.lang.Integer worksId) {
		set("worksId", worksId);
		return (M)this;
	}
	
	public java.lang.Integer getWorksId() {
		return getInt("worksId");
	}

	public M setCreaterId(java.lang.Integer createrId) {
		set("createrId", createrId);
		return (M)this;
	}
	
	public java.lang.Integer getCreaterId() {
		return getInt("createrId");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

}
