package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSmPhotoCollection<M extends BaseSmPhotoCollection<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCreaterId(java.lang.Integer createrId) {
		set("createrId", createrId);
		return (M)this;
	}
	
	public java.lang.Integer getCreaterId() {
		return getInt("createrId");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setIsPraise(java.lang.Boolean isPraise) {
		set("isPraise", isPraise);
		return (M)this;
	}
	
	public java.lang.Boolean getIsPraise() {
		return get("isPraise");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	public M setIsDelete(java.lang.String isDelete) {
		set("isDelete", isDelete);
		return (M)this;
	}
	
	public java.lang.String getIsDelete() {
		return getStr("isDelete");
	}

	public M setStatus(java.lang.Boolean status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Boolean getStatus() {
		return get("status");
	}

}
