package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStartPage<M extends BaseStartPage<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setCover(java.lang.String cover) {
		set("cover", cover);
		return (M)this;
	}
	
	public java.lang.String getCover() {
		return getStr("cover");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setUpdateAt(java.util.Date updateAt) {
		set("updateAt", updateAt);
		return (M)this;
	}
	
	public java.util.Date getUpdateAt() {
		return get("updateAt");
	}

}
