package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSmSysUserAttention<M extends BaseSmSysUserAttention<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setAttentionId(java.lang.Integer attentionId) {
		set("attentionId", attentionId);
		return (M)this;
	}
	
	public java.lang.Integer getAttentionId() {
		return getInt("attentionId");
	}

	public M setCollectionId(java.lang.Integer collectionId) {
		set("collectionId", collectionId);
		return (M)this;
	}
	
	public java.lang.Integer getCollectionId() {
		return getInt("collectionId");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

}
