package com.sandu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSmPhotoProject<M extends BaseSmPhotoProject<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCreaterId(java.lang.Integer createrId) {
		set("createrId", createrId);
		return (M)this;
	}
	
	public java.lang.Integer getCreaterId() {
		return getInt("createrId");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setCover(java.lang.String cover) {
		set("cover", cover);
		return (M)this;
	}
	
	public java.lang.String getCover() {
		return getStr("cover");
	}

	public M setCreateFields(java.lang.String createFields) {
		set("createFields", createFields);
		return (M)this;
	}
	
	public java.lang.String getCreateFields() {
		return getStr("createFields");
	}

	public M setTags(java.lang.String tags) {
		set("tags", tags);
		return (M)this;
	}
	
	public java.lang.String getTags() {
		return getStr("tags");
	}

	public M setImagesPath(java.lang.String imagesPath) {
		set("imagesPath", imagesPath);
		return (M)this;
	}
	
	public java.lang.String getImagesPath() {
		return getStr("imagesPath");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("isDelete", isDelete);
		return (M)this;
	}
	
	public java.lang.Boolean getIsDelete() {
		return get("isDelete");
	}

	public M setPraiseCount(java.lang.Long praiseCount) {
		set("praiseCount", praiseCount);
		return (M)this;
	}
	
	public java.lang.Long getPraiseCount() {
		return getLong("praiseCount");
	}

	public M setViewCount(java.lang.Long viewCount) {
		set("viewCount", viewCount);
		return (M)this;
	}
	
	public java.lang.Long getViewCount() {
		return getLong("viewCount");
	}

	public M setCommentCount(java.lang.Long commentCount) {
		set("commentCount", commentCount);
		return (M)this;
	}
	
	public java.lang.Long getCommentCount() {
		return getLong("commentCount");
	}

	public M setStatus(java.lang.Boolean status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Boolean getStatus() {
		return get("status");
	}

}
