package com.sandu.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("classes", "id", Classes.class);
		arp.addMapping("feedback", "id", Feedback.class);
		arp.addMapping("grade", "id", Grade.class);
		arp.addMapping("parent_account", "id", ParentAccount.class);
		arp.addMapping("school", "id", School.class);
		arp.addMapping("school_account", "id", SchoolAccount.class);
		arp.addMapping("school_introduction", "id", SchoolIntroduction.class);
		arp.addMapping("sensitive_words", "id", SensitiveWords.class);
		arp.addMapping("start_page", "id", StartPage.class);
		arp.addMapping("student", "id", Student.class);
		arp.addMapping("sys_account", "id", SysAccount.class);
		arp.addMapping("sys_adv", "id", SysAdv.class);
		arp.addMapping("sys_info", "id", SysInfo.class);
		arp.addMapping("sys_menu", "id", SysMenu.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_role_menu", "id", SysRoleMenu.class);
		arp.addMapping("sys_session", "id", SysSession.class);
		arp.addMapping("teacher", "id", Teacher.class);
	}
}

