package com.sandu.common.model;

import com.sandu.common.model.base.BaseClasses;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classes extends BaseClasses<Classes> {
	public static final Classes dao = new Classes().dao();
}
