package com.sandu.common.model;

import com.sandu.common.model.base.BaseGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Grade extends BaseGrade<Grade> {
	public static final Grade dao = new Grade().dao();
}
