package com.sandu.common.model;

import com.sandu.common.model.base.BaseParentAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ParentAccount extends BaseParentAccount<ParentAccount> {
	public static final ParentAccount dao = new ParentAccount().dao();
}
