package com.sandu.common.model;

import com.sandu.common.model.base.BaseSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class School extends BaseSchool<School> {
	public static final School dao = new School().dao();
	
	/**
	 * 1 - 正常 0-停用 99-删除 
	 */
	public static final	int STATUS_OK = 1;
	public static final	int STATUS_STOP = 0;
	public static final	int STATUS_DELETE = 99;
	
	
	public boolean isOk(){
		return getStatus() == STATUS_OK;
	}
	
	public boolean isStop(){
		return getStatus() == STATUS_STOP;
	}
	
	public boolean isDelete(){
		return getStatus() == STATUS_DELETE;
	}
}
