package com.sandu.common.model;

import com.sandu.common.model.base.BaseSchoolIntroduction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchoolIntroduction extends BaseSchoolIntroduction<SchoolIntroduction> {
	public static final SchoolIntroduction dao = new SchoolIntroduction().dao();
	
	public static final int	STATUS_WAIT = 0;
	public static final int	STATUS_PASS = 1;
	public static final int	STATUS_REJECT = 2;
	
}
