package com.sandu.common.model;

import com.sandu.common.model.base.BaseSensitiveWords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SensitiveWords extends BaseSensitiveWords<SensitiveWords> {
	public static final SensitiveWords dao = new SensitiveWords().dao();
}
