package com.sandu.common.model;

import com.sandu.common.model.base.BaseSmPhotoCollectionRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmPhotoCollectionRecord extends BaseSmPhotoCollectionRecord<SmPhotoCollectionRecord> {
	public static final SmPhotoCollectionRecord dao = new SmPhotoCollectionRecord().dao();
}
