package com.sandu.common.model;

import com.sandu.common.model.base.BaseSmPhotoProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmPhotoProject extends BaseSmPhotoProject<SmPhotoProject> {
	public static final SmPhotoProject dao = new SmPhotoProject().dao();
}
