package com.sandu.common.model;

import com.sandu.common.model.base.BaseSmSysUserAttention;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmSysUserAttention extends BaseSmSysUserAttention<SmSysUserAttention> {
	public static final SmSysUserAttention dao = new SmSysUserAttention().dao();
}
