package com.sandu.common.model;

import com.sandu.common.model.base.BaseSmSysAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmSysAdmin extends BaseSmSysAdmin<SmSysAdmin> {
	public static final SmSysAdmin dao = new SmSysAdmin().dao();
}
