package com.sandu.common.model;

import com.sandu.common.model.base.BaseSmSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmSysUser extends BaseSmSysUser<SmSysUser> {
	public static final SmSysUser dao = new SmSysUser().dao();
}
