package com.sandu.common.model;

import com.sandu.common.model.base.BaseStartPage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StartPage extends BaseStartPage<StartPage> {
	public static final StartPage dao = new StartPage().dao();
	
	public static final int START_PARENT = 1;
	public static final int START_TEACHER = 2;
}
