package com.sandu.common.model;

import com.sandu.common.model.base.BaseSysInfoSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysInfoSchool extends BaseSysInfoSchool<SysInfoSchool> {
	public static final SysInfoSchool dao = new SysInfoSchool().dao();
}
