package com.sandu.common.model;

import com.sandu.common.model.base.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu().dao();
	
	public static final int STATUS_OK = 1;
	
}
