package com.sandu.common.model;

import com.sandu.common.model.base.BaseSysSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSession extends BaseSysSession<SysSession> {
	public static final SysSession dao = new SysSession().dao();
	
	
	/**
	 * 登录会话是否已过期
	 */
	public boolean isExpired() {
		return getExpireAt() < System.currentTimeMillis();
	}

	/**
	 * 登录会话是否未过期
	 */
	public boolean notExpired() {
		return ! isExpired();
	}
}
