package com.anshuye.common.model;

import com.anshuye.common.model.base.BaseSmPhotoField;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmPhotoField extends BaseSmPhotoField<SmPhotoField> {
	public static final SmPhotoField dao = new SmPhotoField().dao();
}
