package com.anshuye.common.model;

import com.anshuye.common.model.base.BaseSmPhotoComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmPhotoComment extends BaseSmPhotoComment<SmPhotoComment> {
	public static final SmPhotoComment dao = new SmPhotoComment().dao();
}
