package com.anshuye.common.model;

import com.anshuye.common.model.base.BaseSmPhotoCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmPhotoCollection extends BaseSmPhotoCollection<SmPhotoCollection> {
	public static final SmPhotoCollection dao = new SmPhotoCollection().dao();
}
