package com.anshuye.common.model;

import com.anshuye.common.model.base.BaseSmPhotoPraise;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmPhotoPraise extends BaseSmPhotoPraise<SmPhotoPraise> {
	public static final SmPhotoPraise dao = new SmPhotoPraise().dao();
}
