package com.anshuye.common.model;

import com.anshuye.common.model.base.BaseSmSysMeassage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmSysMeassage extends BaseSmSysMeassage<SmSysMeassage> {
	public static final SmSysMeassage dao = new SmSysMeassage().dao();
}
