package com.anshuye.common.model;

import com.anshuye.common.model.base.BaseSmSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmSysUser extends BaseSmSysUser<SmSysUser> {
	public static final SmSysUser dao = new SmSysUser().dao();
	
	public SmSysUser removeSensitiveInfo() {
		return this.remove("password","salt");
	}
}
