package com.anshuye.common.model;

import com.anshuye.common.model.base.BaseSysAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAccount extends BaseSysAccount<SysAccount> {
	public static final SysAccount dao = new SysAccount().dao();
	
	public static final int STATUS_LOCK = 0;	
	public static final int STATUS_OK = 1;		
	public static final int SYS_ADMIN = 0;		

	public boolean isStatusOk() {
		return getStatus() == STATUS_OK;
	}


	public boolean isStatusLockId() {
		return getStatus() == STATUS_LOCK;
	}
	
	public boolean isSysAdmin(){
		return getRoleId() == SYS_ADMIN;
	}


	public SysAccount removeSensitiveInfo() {
		return this.remove("password","salt");
	}

}
