package com.anshuye.common.model;

import com.anshuye.common.model.base.BaseSysAdv;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAdv extends BaseSysAdv<SysAdv> {
	public static final SysAdv dao = new SysAdv().dao();
}
