package com.anshuye.common.model;

import com.anshuye.common.model.base.BaseSysInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysInfo extends BaseSysInfo<SysInfo> {
	public static final SysInfo dao = new SysInfo().dao();
}
