package com.anshuye.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSmPhotoField<M extends BaseSmPhotoField<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setFieldName(java.lang.String fieldName) {
		set("fieldName", fieldName);
		return (M)this;
	}
	
	public java.lang.String getFieldName() {
		return getStr("fieldName");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setProviderId(java.lang.Integer providerId) {
		set("providerId", providerId);
		return (M)this;
	}
	
	public java.lang.Integer getProviderId() {
		return getInt("providerId");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
